<a href="https://colab.research.google.com/github/ablet-imin/tensorflow_training/blob/main/tf_quick_start.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Load data
2. Build a NN for image classification
3. Train NN
4. Evaluate accuracy of the model

In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.2


***Load mnist dataset***

In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255. , x_test/255.

11501568/11490434 [==============================] - 0s 0us/step


Ten digit 0-9, total of 10 classes.  
Build a model, imput 28$\times$28.  
Output is 10

In [5]:
model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Flatten(input_shape=(28,28)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10)
    ]
)

In [7]:
prediction = model(x_train[:1]).numpy()
prediction 


array([[ 0.0968871 ,  0.29094854, -0.15103205, -0.1547938 , -0.03443533,
         0.04045326, -0.28295588, -0.7244658 ,  0.5221679 , -0.22851121]],
      dtype=float32)

In [8]:
tf.nn.softmax(prediction)

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.11148003, 0.13535582, 0.08700158, 0.08667493, 0.09776075,
        0.10536302, 0.07624887, 0.04903296, 0.1705667 , 0.0805153 ]],
      dtype=float32)>

Add loss fuction

In [10]:
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
loss(y_train[:1], prediction).numpy()

2.2503436

In [12]:
from tensorflow.python import metrics
#compile model 

model.compile(optimizer='adam', loss=loss, metrics=['accuracy'])

In [13]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2962 - accuracy: 0.9137
Epoch 2/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1412 - accuracy: 0.9587
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1060 - accuracy: 0.9677
Epoch 4/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0877 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0743 - accuracy: 0.9767


# Evaluate

In [14]:
model.evaluate(x_test,y_test, verbose=2)

313/313 - 1s - loss: 0.0694 - accuracy: 0.9800 - 567ms/epoch - 2ms/step


[0.06935399025678635, 0.9800000190734863]

Model is 98% accurate

# How to wrape model. 
This can be used to compine two models as well

In [15]:
probabilistic_model = tf.keras.models.Sequential(
    [
        model, #this is already trained model
        tf.keras.layers.Softmax() # Add new layers or this could be another model.
    ]
)

In [16]:
probabilistic_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.46144250e-08, 1.22357520e-07, 2.73654568e-05, 9.48036206e-04,
        9.27557475e-10, 2.68834606e-06, 2.46140050e-13, 9.98977542e-01,
        6.64424033e-06, 3.74826341e-05],
       [2.59250998e-09, 3.08463495e-04, 9.99643445e-01, 8.20271634e-06,
        2.66151410e-15, 3.96164287e-05, 1.31295086e-09, 2.86267381e-11,
        1.87544060e-07, 2.72580014e-11],
       [1.13263106e-07, 9.98586535e-01, 3.26311652e-04, 1.45094418e-05,
        1.67961873e-04, 3.52916823e-06, 3.62797596e-06, 7.39332580e-04,
        1.54740948e-04, 3.25813176e-06],
       [9.99949455e-01, 1.23593411e-08, 2.80771492e-05, 2.03471345e-07,
        8.78819435e-08, 6.78621927e-06, 5.60753597e-06, 7.12783560e-07,
        1.10842944e-08, 8.94241111e-06],
       [5.40757583e-06, 1.52142104e-06, 9.58836608e-05, 9.70660039e-07,
        9.97153163e-01, 3.74887691e-06, 1.04674189e-06, 8.73706187e-04,
        9.52194023e-06, 1.85503974e-03]], dtype=float32)>